### ISSUE TITLE
Division entre 0 police

### ISSUE THREAD

**Issue by Wlgen** [Wlgen/Kojiman#1]
https://github.com/Wlgen/Kojiman/blob/cb6cc44452e515b8b1071f8c87b196fbd86650d7/2DGame/02-Bubble/02-Bubble/Police.cpp#L34-L57
La cosa es que si el valor de la x o la y en el momento de detectar la posicion del player es la misma la division para calcular Ymov se hace la division entre 0.

**Comment by ArnauGP3599** [comment]
Pos ya estaria
